- name: Update all packages to their latest version
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 600
  become: true
  when: update_system

- name: Update repositories cache and install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    update_cache: true
    cache_valid_time: 600
  become: true
  when: update_system

- name: Set timezone to Europe/Amsterdam
  become: true
  community.general.timezone:
    name: Europe/Amsterdam

- name: Ensure timesync is enabled and restarted
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true
  become: true

- name: Upload new template
  ansible.builtin.template:
    src: 'journald.conf.j2'
    dest: '/etc/systemd/journald.conf'
    mode: '0755'
  become: true # <-- unless you are connecting as root
  notify: Reload systemd-journald

